version: '2'

networks:
  back-tier:
    driver: bridge
    
services:
  sinatra:
    #restart: unless-stopped
    image: erikap/ruby-sinatra
    environment:
      - MAIN_APP_FILE=myapp.rb
    ports:
      - "8090:8090"
    volumes:
      - ./:/usr/src/app
    networks:
      - back-tier